# Generated by Django 4.1.5 on 2023-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=60)),
                ('headquarters_country', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
    ]
