# Generated by Django 4.1.5 on 2023-01-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["price"],
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
    ]
