# Generated by Django 4.1.5 on 2023-01-19 19:36

import car.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(validators=[car.validators.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[car.validators.validate_nonnegative]),
        ),
    ]
