# Generated by Django 4.1.5 on 2023-01-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=60)),
                ("issue_year", models.IntegerField()),
                ("body_style", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
    ]
